spring:
  application:
    name: frotas

  datasource:
    url: jdbc:mysql://localhost:3307/triunfodb
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true


jwt:
  secret: novotriunfo-secret
  expiration: 3600000

server:
  error:
    include-message: always
    include-binding-errors: always